TRUNCATE TABLE symbols CASCADE;

INSERT INTO symbols (code, name, market) VALUES
-- 時価総額上位（メガキャップ）
('NVDA', 'NVIDIA Corp', 'NASDAQ'),
('AAPL', 'Apple Inc.', 'NASDAQ'),
('GOOGL', 'Alphabet Inc. (Class A)', 'NASDAQ'),
('MSFT', 'Microsoft Corp.', 'NASDAQ'),
('AMZN', 'Amazon.com Inc.', 'NASDAQ'),
('AVGO', 'Broadcom Inc.', 'NASDAQ'),
('META', 'Meta Platforms, Inc.', 'NASDAQ'),
('TSLA', 'Tesla, Inc.', 'NASDAQ'),
('BRK.B', 'Berkshire Hathaway Inc.', 'NYSE'),
('LLY', 'Eli Lilly and Company', 'NYSE'),
-- 情報技術 - 半導体
('QCOM', 'Qualcomm Inc.', 'NASDAQ'),
('AMD', 'Advanced Micro Devices Inc.', 'NASDAQ'),
('INTC', 'Intel Corp.', 'NASDAQ'),
('TXN', 'Texas Instruments Inc.', 'NASDAQ'),
('AMAT', 'Applied Materials Inc.', 'NASDAQ'),
('LRCX', 'Lam Research Corp.', 'NASDAQ'),
('KLAC', 'KLA Corp.', 'NASDAQ'),
('MU', 'Micron Technology Inc.', 'NASDAQ'),
('ADI', 'Analog Devices Inc.', 'NASDAQ'),
('MCHP', 'Microchip Technology Inc.', 'NASDAQ'),
('NXPI', 'NXP Semiconductors N.V.', 'NASDAQ'),
('CDNS', 'Cadence Design Systems Inc.', 'NASDAQ'),
('SNPS', 'Synopsys Inc.', 'NASDAQ'),
-- 情報技術 - ハードウェア・ネットワーク
('CSCO', 'Cisco Systems Inc.', 'NASDAQ'),
('IBM', 'International Business Machines Corp.', 'NYSE'),
('HPE', 'Hewlett Packard Enterprise Co.', 'NYSE'),
('HPQ', 'HP Inc.', 'NYSE'),
('DELL', 'Dell Technologies Inc.', 'NYSE'),
('STX', 'Seagate Technology Holdings plc', 'NASDAQ'),
('WDC', 'Western Digital Corp.', 'NASDAQ'),
-- 情報技術 - エンタープライズソフトウェア
('ORCL', 'Oracle Corp.', 'NYSE'),
('NOW', 'ServiceNow Inc.', 'NYSE'),
('CRM', 'Salesforce Inc.', 'NYSE'),
('ADBE', 'Adobe Inc.', 'NASDAQ'),
('INTU', 'Intuit Inc.', 'NASDAQ'),
('ROP', 'Roper Technologies Inc.', 'NASDAQ'),
('IT', 'Gartner Inc.', 'NYSE'),
-- 情報技術 - クラウド・SaaS
('WDAY', 'Workday Inc.', 'NASDAQ'),
('VEEV', 'Veeva Systems Inc.', 'NYSE'),
('PAYC', 'Paycom Software Inc.', 'NYSE'),
('MDB', 'MongoDB Inc.', 'NASDAQ'),
('SNOW', 'Snowflake Inc.', 'NYSE'),
('DDOG', 'Datadog Inc.', 'NASDAQ'),
('TEAM', 'Atlassian Corp.', 'NASDAQ'),
-- 情報技術 - サイバーセキュリティ
('PANW', 'Palo Alto Networks Inc.', 'NASDAQ'),
('FTNT', 'Fortinet Inc.', 'NASDAQ'),
('CRWD', 'CrowdStrike Holdings Inc.', 'NASDAQ'),
('ZS', 'Zscaler Inc.', 'NASDAQ'),
-- 情報技術 - ITサービス・フィンテック
('ACN', 'Accenture plc', 'NYSE'),
('CTSH', 'Cognizant Technology Solutions Corp.', 'NASDAQ'),
('FI', 'Fidelity National Information Services Inc.', 'NYSE'),
('FISV', 'Fiserv Inc.', 'NASDAQ'),
('GPN', 'Global Payments Inc.', 'NYSE'),
('PYPL', 'PayPal Holdings Inc.', 'NASDAQ'),
('FTV', 'Fortive Corp.', 'NYSE'),
('AME', 'AMETEK Inc.', 'NYSE'),
-- ヘルスケア - 製薬
('JNJ', 'Johnson & Johnson', 'NYSE'),
('UNH', 'UnitedHealth Group Inc.', 'NYSE'),
('ABBV', 'AbbVie Inc.', 'NYSE'),
('MRK', 'Merck & Co. Inc.', 'NYSE'),
('PFE', 'Pfizer Inc.', 'NYSE'),
('BMY', 'Bristol-Myers Squibb Co.', 'NYSE'),
('AMGN', 'Amgen Inc.', 'NASDAQ'),
('GILD', 'Gilead Sciences Inc.', 'NASDAQ'),
('REGN', 'Regeneron Pharmaceuticals Inc.', 'NASDAQ'),
('VRTX', 'Vertex Pharmaceuticals Inc.', 'NASDAQ'),
('BIIB', 'Biogen Inc.', 'NASDAQ'),
('MRNA', 'Moderna Inc.', 'NASDAQ'),
-- ヘルスケア - 医療機器
('TMO', 'Thermo Fisher Scientific Inc.', 'NYSE'),
('ABT', 'Abbott Laboratories', 'NYSE'),
('MDT', 'Medtronic plc', 'NYSE'),
('BSX', 'Boston Scientific Corp.', 'NYSE'),
('SYK', 'Stryker Corp.', 'NYSE'),
('EW', 'Edwards Lifesciences Corp.', 'NYSE'),
('BDX', 'Becton Dickinson and Co.', 'NYSE'),
('ZBH', 'Zimmer Biomet Holdings Inc.', 'NYSE'),
('BAX', 'Baxter International Inc.', 'NYSE'),
('RMD', 'ResMed Inc.', 'NYSE'),
('DXCM', 'DexCom Inc.', 'NASDAQ'),
('IDXX', 'IDEXX Laboratories Inc.', 'NASDAQ'),
('HOLX', 'Hologic Inc.', 'NASDAQ'),
('ALGN', 'Align Technology Inc.', 'NASDAQ'),
('ISRG', 'Intuitive Surgical Inc.', 'NASDAQ'),
('A', 'Agilent Technologies Inc.', 'NYSE'),
-- ヘルスケア - マネージドケア・流通
('IQV', 'IQVIA Holdings Inc.', 'NYSE'),
('MCK', 'McKesson Corp.', 'NYSE'),
('CAH', 'Cardinal Health Inc.', 'NYSE'),
('CNC', 'Centene Corp.', 'NYSE'),
('HUM', 'Humana Inc.', 'NYSE'),
('CI', 'Cigna Group', 'NYSE'),
('ELV', 'Elevance Health Inc.', 'NYSE'),
('CVS', 'CVS Health Corp.', 'NYSE'),
('HCA', 'HCA Healthcare Inc.', 'NYSE'),
('UHS', 'Universal Health Services Inc.', 'NYSE'),
-- 金融 - 銀行
('JPM', 'JPMorgan Chase & Co.', 'NYSE'),
('BAC', 'Bank of America Corp.', 'NYSE'),
('WFC', 'Wells Fargo & Co.', 'NYSE'),
('C', 'Citigroup Inc.', 'NYSE'),
('USB', 'U.S. Bancorp', 'NYSE'),
('TFC', 'Truist Financial Corp.', 'NYSE'),
('PNC', 'PNC Financial Services Group Inc.', 'NYSE'),
('MTB', 'M&T Bank Corp.', 'NYSE'),
('CFG', 'Citizens Financial Group Inc.', 'NYSE'),
('FITB', 'Fifth Third Bancorp', 'NASDAQ'),
('KEY', 'KeyCorp', 'NYSE'),
('HBAN', 'Huntington Bancshares Inc.', 'NASDAQ'),
('RF', 'Regions Financial Corp.', 'NYSE'),
-- 金融 - 決済・クレジット
('V', 'Visa Inc.', 'NYSE'),
('MA', 'Mastercard Inc.', 'NYSE'),
('AXP', 'American Express Co.', 'NYSE'),
('COF', 'Capital One Financial Corp.', 'NYSE'),
('SYF', 'Synchrony Financial', 'NYSE'),
-- 金融 - 資産運用・証券
('GS', 'Goldman Sachs Group Inc.', 'NYSE'),
('MS', 'Morgan Stanley', 'NYSE'),
('BLK', 'BlackRock Inc.', 'NYSE'),
('SCHW', 'Charles Schwab Corp.', 'NYSE'),
('BX', 'Blackstone Inc.', 'NYSE'),
('KKR', 'KKR & Co. Inc.', 'NYSE'),
('STT', 'State Street Corp.', 'NYSE'),
('BK', 'Bank of New York Mellon Corp.', 'NYSE'),
('TROW', 'T. Rowe Price Group Inc.', 'NASDAQ'),
-- 金融 - 保険
('AIG', 'American International Group Inc.', 'NYSE'),
('MET', 'MetLife Inc.', 'NYSE'),
('PRU', 'Prudential Financial Inc.', 'NYSE'),
('AFL', 'Aflac Inc.', 'NYSE'),
('TRV', 'Travelers Companies Inc.', 'NYSE'),
('ALL', 'Allstate Corp.', 'NYSE'),
('PGR', 'Progressive Corp.', 'NYSE'),
('CB', 'Chubb Ltd.', 'NYSE'),
('HIG', 'Hartford Financial Services Group Inc.', 'NYSE'),
('CINF', 'Cincinnati Financial Corp.', 'NASDAQ'),
-- 金融 - 金融サービス・取引所
('MMC', 'Marsh & McLennan Companies Inc.', 'NYSE'),
('AON', 'Aon plc', 'NYSE'),
('WTW', 'Willis Towers Watson plc', 'NASDAQ'),
('ICE', 'Intercontinental Exchange Inc.', 'NYSE'),
('CME', 'CME Group Inc.', 'NASDAQ'),
('CBOE', 'Cboe Global Markets Inc.', 'NYSE'),
('NDAQ', 'Nasdaq Inc.', 'NASDAQ'),
('SPGI', 'S&P Global Inc.', 'NYSE'),
('MCO', 'Moody''s Corp.', 'NYSE'),
('FDS', 'FactSet Research Systems Inc.', 'NASDAQ'),
('MSCI', 'MSCI Inc.', 'NYSE'),
-- 一般消費財 - 小売
('HD', 'Home Depot Inc.', 'NYSE'),
('LOW', 'Lowe''s Companies Inc.', 'NYSE'),
('TJX', 'TJX Companies Inc.', 'NYSE'),
('ROST', 'Ross Stores Inc.', 'NASDAQ'),
('BBY', 'Best Buy Co. Inc.', 'NYSE'),
('KMX', 'CarMax Inc.', 'NYSE'),
('AZO', 'AutoZone Inc.', 'NYSE'),
('ORLY', 'O''Reilly Automotive Inc.', 'NASDAQ'),
('ULTA', 'Ulta Beauty Inc.', 'NASDAQ'),
('TSCO', 'Tractor Supply Co.', 'NASDAQ'),
('EBAY', 'eBay Inc.', 'NASDAQ'),
('ETSY', 'Etsy Inc.', 'NASDAQ'),
-- 一般消費財 - レストラン
('MCD', 'McDonald''s Corp.', 'NYSE'),
('SBUX', 'Starbucks Corp.', 'NASDAQ'),
('YUM', 'Yum! Brands Inc.', 'NYSE'),
('CMG', 'Chipotle Mexican Grill Inc.', 'NYSE'),
('DRI', 'Darden Restaurants Inc.', 'NYSE'),
-- 一般消費財 - 旅行・ホテル
('BKNG', 'Booking Holdings Inc.', 'NASDAQ'),
('ABNB', 'Airbnb Inc.', 'NASDAQ'),
('MAR', 'Marriott International Inc.', 'NASDAQ'),
('HLT', 'Hilton Worldwide Holdings Inc.', 'NYSE'),
('RCL', 'Royal Caribbean Cruises Ltd.', 'NYSE'),
('CCL', 'Carnival Corp.', 'NYSE'),
-- 一般消費財 - 自動車
('GM', 'General Motors Co.', 'NYSE'),
('F', 'Ford Motor Co.', 'NYSE'),
('APTV', 'Aptiv plc', 'NYSE'),
('BWA', 'BorgWarner Inc.', 'NYSE'),
('LEA', 'Lear Corp.', 'NYSE'),
('LKQ', 'LKQ Corp.', 'NASDAQ'),
('UBER', 'Uber Technologies Inc.', 'NYSE'),
-- 一般消費財 - 住宅建設
('DHI', 'D.R. Horton Inc.', 'NYSE'),
('LEN', 'Lennar Corp.', 'NYSE'),
('PHM', 'PulteGroup Inc.', 'NYSE'),
('TOL', 'Toll Brothers Inc.', 'NYSE'),
('NVR', 'NVR Inc.', 'NYSE'),
('POOL', 'Pool Corp.', 'NASDAQ'),
-- 一般消費財 - その他
('NKE', 'NIKE Inc.', 'NYSE'),
('GRMN', 'Garmin Ltd.', 'NASDAQ'),
-- 生活必需品 - 家庭用品
('PG', 'Procter & Gamble Co.', 'NYSE'),
('CL', 'Colgate-Palmolive Co.', 'NYSE'),
('CHD', 'Church & Dwight Co.', 'NYSE'),
('EL', 'Estee Lauder Companies Inc.', 'NYSE'),
-- 生活必需品 - 飲料
('KO', 'Coca-Cola Co.', 'NYSE'),
('PEP', 'PepsiCo Inc.', 'NASDAQ'),
('MNST', 'Monster Beverage Corp.', 'NASDAQ'),
('KDP', 'Keurig Dr Pepper Inc.', 'NASDAQ'),
('STZ', 'Constellation Brands Inc.', 'NYSE'),
('TAP', 'Molson Coors Beverage Co.', 'NYSE'),
-- 生活必需品 - 食品・小売
('WMT', 'Walmart Inc.', 'NYSE'),
('COST', 'Costco Wholesale Corp.', 'NASDAQ'),
('KR', 'Kroger Co.', 'NYSE'),
('SYY', 'Sysco Corp.', 'NYSE'),
('MDLZ', 'Mondelez International Inc.', 'NASDAQ'),
('KHC', 'Kraft Heinz Co.', 'NASDAQ'),
('GIS', 'General Mills Inc.', 'NYSE'),
('CAG', 'Conagra Brands Inc.', 'NYSE'),
('CPB', 'Campbell Soup Co.', 'NYSE'),
('MKC', 'McCormick & Company Inc.', 'NYSE'),
('HSY', 'Hershey Co.', 'NYSE'),
('SJM', 'J.M. Smucker Co.', 'NYSE'),
('HRL', 'Hormel Foods Corp.', 'NYSE'),
('TSN', 'Tyson Foods Inc.', 'NYSE'),
('ADM', 'Archer-Daniels-Midland Co.', 'NYSE'),
('BG', 'Bunge Global SA', 'NYSE'),
-- 生活必需品 - タバコ
('MO', 'Altria Group Inc.', 'NYSE'),
('PM', 'Philip Morris International Inc.', 'NYSE'),
-- エネルギー - 探査・生産
('XOM', 'Exxon Mobil Corp.', 'NYSE'),
('CVX', 'Chevron Corp.', 'NYSE'),
('COP', 'ConocoPhillips', 'NYSE'),
('EOG', 'EOG Resources Inc.', 'NYSE'),
('DVN', 'Devon Energy Corp.', 'NYSE'),
('OXY', 'Occidental Petroleum Corp.', 'NYSE'),
('CTRA', 'Coterra Energy Inc.', 'NYSE'),
('FANG', 'Diamondback Energy Inc.', 'NASDAQ'),
('EQT', 'EQT Corp.', 'NYSE'),
('RRC', 'Range Resources Corp.', 'NYSE'),
('AR', 'Antero Resources Corp.', 'NYSE'),
-- エネルギー - 油田サービス・精製
('SLB', 'Schlumberger Ltd.', 'NYSE'),
('HAL', 'Halliburton Co.', 'NYSE'),
('BKR', 'Baker Hughes Co.', 'NASDAQ'),
('APA', 'APA Corp.', 'NASDAQ'),
('MPC', 'Marathon Petroleum Corp.', 'NYSE'),
('VLO', 'Valero Energy Corp.', 'NYSE'),
('PSX', 'Phillips 66', 'NYSE'),
-- 素材 - 化学
('LIN', 'Linde plc', 'NASDAQ'),
('APD', 'Air Products and Chemicals Inc.', 'NYSE'),
('ECL', 'Ecolab Inc.', 'NYSE'),
('DD', 'DuPont de Nemours Inc.', 'NYSE'),
('DOW', 'Dow Inc.', 'NYSE'),
('LYB', 'LyondellBasell Industries N.V.', 'NYSE'),
('CE', 'Celanese Corp.', 'NYSE'),
('EMN', 'Eastman Chemical Co.', 'NYSE'),
('FMC', 'FMC Corp.', 'NYSE'),
('IFF', 'International Flavors & Fragrances Inc.', 'NYSE'),
('CF', 'CF Industries Holdings Inc.', 'NYSE'),
('MOS', 'Mosaic Co.', 'NYSE'),
-- 素材 - 塗料
('SHW', 'Sherwin-Williams Co.', 'NYSE'),
('PPG', 'PPG Industries Inc.', 'NYSE'),
('RPM', 'RPM International Inc.', 'NYSE'),
-- 素材 - 鉱業・金属
('NEM', 'Newmont Corp.', 'NYSE'),
('FCX', 'Freeport-McMoRan Inc.', 'NYSE'),
('NUE', 'Nucor Corp.', 'NYSE'),
('STLD', 'Steel Dynamics Inc.', 'NASDAQ'),
('CLF', 'Cleveland-Cliffs Inc.', 'NYSE'),
('AA', 'Alcoa Corp.', 'NYSE'),
-- 素材 - 建設資材・包装
('VMC', 'Vulcan Materials Co.', 'NYSE'),
('MLM', 'Martin Marietta Materials Inc.', 'NYSE'),
('RS', 'Reliance Inc.', 'NYSE'),
('ALB', 'Albemarle Corp.', 'NYSE'),
('SEE', 'Sealed Air Corp.', 'NYSE'),
('AVY', 'Avery Dennison Corp.', 'NYSE'),
('PKG', 'Packaging Corp. of America', 'NYSE'),
('IP', 'International Paper Co.', 'NYSE'),
-- 資本財 - 防衛・航空宇宙
('RTX', 'RTX Corp.', 'NYSE'),
('LMT', 'Lockheed Martin Corp.', 'NYSE'),
('NOC', 'Northrop Grumman Corp.', 'NYSE'),
('GD', 'General Dynamics Corp.', 'NYSE'),
('HII', 'Huntington Ingalls Industries Inc.', 'NYSE'),
('LHX', 'L3Harris Technologies Inc.', 'NYSE'),
('TDG', 'TransDigm Group Inc.', 'NYSE'),
('TXT', 'Textron Inc.', 'NYSE'),
('LDOS', 'Leidos Holdings Inc.', 'NYSE'),
('SAIC', 'Science Applications International Corp.', 'NYSE'),
('BAH', 'Booz Allen Hamilton Holding Corp.', 'NYSE'),
('CACI', 'CACI International Inc.', 'NYSE'),
('AXON', 'Axon Enterprise Inc.', 'NASDAQ'),
-- 資本財 - 航空・宇宙
('GE', 'GE Aerospace', 'NYSE'),
('BA', 'Boeing Co.', 'NYSE'),
-- 資本財 - 産業機械
('CAT', 'Caterpillar Inc.', 'NYSE'),
('DE', 'Deere & Company', 'NYSE'),
('HON', 'Honeywell International Inc.', 'NASDAQ'),
('ETN', 'Eaton Corp. plc', 'NYSE'),
('EMR', 'Emerson Electric Co.', 'NYSE'),
('PH', 'Parker-Hannifin Corp.', 'NYSE'),
('ITW', 'Illinois Tool Works Inc.', 'NYSE'),
('ROK', 'Rockwell Automation Inc.', 'NYSE'),
('IR', 'Ingersoll Rand Inc.', 'NYSE'),
('XYL', 'Xylem Inc.', 'NYSE'),
('OTIS', 'Otis Worldwide Corp.', 'NYSE'),
('CARR', 'Carrier Global Corp.', 'NYSE'),
('TT', 'Trane Technologies plc', 'NYSE'),
('JCI', 'Johnson Controls International plc', 'NYSE'),
('DOV', 'Dover Corp.', 'NYSE'),
('SNA', 'Snap-on Inc.', 'NYSE'),
('SWK', 'Stanley Black & Decker Inc.', 'NYSE'),
('GNRC', 'Generac Holdings Inc.', 'NYSE'),
('HUBB', 'Hubbell Inc.', 'NYSE'),
-- 資本財 - 物流・輸送
('UPS', 'United Parcel Service Inc.', 'NYSE'),
('FDX', 'FedEx Corp.', 'NYSE'),
('UNP', 'Union Pacific Corp.', 'NYSE'),
('CSX', 'CSX Corp.', 'NASDAQ'),
('NSC', 'Norfolk Southern Corp.', 'NYSE'),
('EXPD', 'Expeditors International of Washington Inc.', 'NASDAQ'),
('CHRW', 'C.H. Robinson Worldwide Inc.', 'NASDAQ'),
('JBHT', 'J.B. Hunt Transport Services Inc.', 'NASDAQ'),
('ODFL', 'Old Dominion Freight Line Inc.', 'NASDAQ'),
('WAB', 'Westinghouse Air Brake Technologies Corp.', 'NYSE'),
-- 資本財 - 廃棄物・その他サービス
('WM', 'Waste Management Inc.', 'NYSE'),
('RSG', 'Republic Services Inc.', 'NYSE'),
('CPRT', 'Copart Inc.', 'NASDAQ'),
('VRSK', 'Verisk Analytics Inc.', 'NASDAQ'),
('GWW', 'W.W. Grainger Inc.', 'NYSE'),
('FAST', 'Fastenal Co.', 'NASDAQ'),
('BR', 'Broadridge Financial Solutions Inc.', 'NYSE'),
('ADP', 'Automatic Data Processing Inc.', 'NASDAQ'),
('PAYX', 'Paychex Inc.', 'NASDAQ'),
('J', 'Jacobs Solutions Inc.', 'NYSE'),
('PWR', 'Quanta Services Inc.', 'NYSE'),
-- 公益事業
('NEE', 'NextEra Energy Inc.', 'NYSE'),
('DUK', 'Duke Energy Corp.', 'NYSE'),
('SO', 'Southern Co.', 'NYSE'),
('AEP', 'American Electric Power Co. Inc.', 'NASDAQ'),
('EXC', 'Exelon Corp.', 'NASDAQ'),
('SRE', 'Sempra', 'NYSE'),
('D', 'Dominion Energy Inc.', 'NYSE'),
('PCG', 'PG&E Corp.', 'NYSE'),
('ED', 'Consolidated Edison Inc.', 'NYSE'),
('ETR', 'Entergy Corp.', 'NYSE'),
('FE', 'FirstEnergy Corp.', 'NYSE'),
('EIX', 'Edison International', 'NYSE'),
('ES', 'Eversource Energy', 'NYSE'),
('XEL', 'Xcel Energy Inc.', 'NASDAQ'),
('CMS', 'CMS Energy Corp.', 'NYSE'),
('DTE', 'DTE Energy Co.', 'NYSE'),
('AES', 'AES Corp.', 'NYSE'),
('LNT', 'Alliant Energy Corp.', 'NASDAQ'),
('CNP', 'CenterPoint Energy Inc.', 'NYSE'),
('NI', 'NiSource Inc.', 'NYSE'),
('AEE', 'Ameren Corp.', 'NYSE'),
('WEC', 'WEC Energy Group Inc.', 'NYSE'),
('AWK', 'American Water Works Co. Inc.', 'NYSE'),
('PPL', 'PPL Corp.', 'NYSE'),
('EVRG', 'Evergy Inc.', 'NASDAQ'),
('VST', 'Vistra Corp.', 'NYSE'),
('CEG', 'Constellation Energy Corp.', 'NASDAQ'),
-- 不動産 - 通信タワー
('AMT', 'American Tower Corp.', 'NYSE'),
('CCI', 'Crown Castle Inc.', 'NYSE'),
('SBAC', 'SBA Communications Corp.', 'NASDAQ'),
-- 不動産 - データセンター・ストレージ
('EQIX', 'Equinix Inc.', 'NASDAQ'),
('DLR', 'Digital Realty Trust Inc.', 'NYSE'),
('IRM', 'Iron Mountain Inc.', 'NYSE'),
-- 不動産 - 産業・物流
('PLD', 'Prologis Inc.', 'NYSE'),
-- 不動産 - 商業施設
('SPG', 'Simon Property Group Inc.', 'NYSE'),
('KIM', 'Kimco Realty Corp.', 'NYSE'),
('REG', 'Regency Centers Corp.', 'NASDAQ'),
-- 不動産 - 住宅
('EQR', 'Equity Residential', 'NYSE'),
('AVB', 'AvalonBay Communities Inc.', 'NYSE'),
('MAA', 'Mid-America Apartment Communities Inc.', 'NYSE'),
('INVH', 'Invitation Homes Inc.', 'NYSE'),
-- 不動産 - ヘルスケア
('VTR', 'Ventas Inc.', 'NYSE'),
('WELL', 'Welltower Inc.', 'NYSE'),
-- 不動産 - ネットリース
('O', 'Realty Income Corp.', 'NYSE'),
('VICI', 'VICI Properties Inc.', 'NYSE'),
('NNN', 'NNN REIT Inc.', 'NYSE'),
-- 不動産 - オフィス
('ARE', 'Alexandria Real Estate Equities Inc.', 'NYSE'),
('BXP', 'BXP Inc.', 'NYSE'),
-- 不動産 - セルフストレージ
('PSA', 'Public Storage', 'NYSE'),
('EXR', 'Extra Space Storage Inc.', 'NYSE'),
('CUBE', 'CubeSmart', 'NYSE'),
-- 不動産 - その他
('CBRE', 'CBRE Group Inc.', 'NYSE'),
('WY', 'Weyerhaeuser Co.', 'NYSE'),
('HST', 'Host Hotels & Resorts Inc.', 'NASDAQ'),
-- 通信サービス - メディア・エンターテイメント
('GOOG', 'Alphabet Inc. (Class C)', 'NASDAQ'),
('NFLX', 'Netflix Inc.', 'NASDAQ'),
('DIS', 'Walt Disney Co.', 'NYSE'),
('CMCSA', 'Comcast Corp.', 'NASDAQ'),
('WBD', 'Warner Bros. Discovery Inc.', 'NASDAQ'),
('FOXA', 'Fox Corp. (Class A)', 'NASDAQ'),
('FOX', 'Fox Corp. (Class B)', 'NASDAQ'),
('LYV', 'Live Nation Entertainment Inc.', 'NYSE'),
-- 通信サービス - 通信キャリア
('T', 'AT&T Inc.', 'NYSE'),
('VZ', 'Verizon Communications Inc.', 'NYSE'),
('TMUS', 'T-Mobile US Inc.', 'NASDAQ'),
('CHTR', 'Charter Communications Inc.', 'NASDAQ'),
-- 通信サービス - 広告・デジタル
('TTD', 'Trade Desk Inc.', 'NASDAQ'),
('OMC', 'Omnicom Group Inc.', 'NYSE'),
('MTCH', 'Match Group Inc.', 'NASDAQ')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  market = EXCLUDED.market;

INSERT INTO symbols (code, name, market) VALUES
-- 情報技術 - 半導体追加
('ENPH', 'Enphase Energy Inc.', 'NASDAQ'),
('FSLR', 'First Solar Inc.', 'NASDAQ'),
('MPWR', 'Monolithic Power Systems Inc.', 'NASDAQ'),
('ON', 'ON Semiconductor Corp.', 'NASDAQ'),
('SWKS', 'Skyworks Solutions Inc.', 'NASDAQ'),
-- 情報技術 - テスト・計測
('KEYS', 'Keysight Technologies Inc.', 'NYSE'),
('TER', 'Teradyne Inc.', 'NASDAQ'),
('TDY', 'Teledyne Technologies Inc.', 'NYSE'),
-- 情報技術 - ソフトウェア・ネットワーク追加
('FFIV', 'F5 Inc.', 'NASDAQ'),
('AKAM', 'Akamai Technologies Inc.', 'NASDAQ'),
('VRSN', 'VeriSign Inc.', 'NASDAQ'),
('NTAP', 'NetApp Inc.', 'NASDAQ'),
('ZBRA', 'Zebra Technologies Corp.', 'NASDAQ'),
('CDW', 'CDW Corp.', 'NASDAQ'),
('FICO', 'Fair Isaac Corp.', 'NYSE'),
('PTC', 'PTC Inc.', 'NASDAQ'),
-- ヘルスケア - 医療機器追加
('GEHC', 'GE HealthCare Technologies Inc.', 'NASDAQ'),
('NTRA', 'Natera Inc.', 'NASDAQ'),
('PODD', 'Insulet Corp.', 'NASDAQ'),
('COO', 'Cooper Companies Inc.', 'NYSE'),
('CRL', 'Charles River Laboratories International Inc.', 'NYSE'),
('MTD', 'Mettler-Toledo International Inc.', 'NYSE'),
('WAT', 'Waters Corp.', 'NYSE'),
('STE', 'Steris plc', 'NYSE'),
('RVTY', 'Revvity Inc.', 'NYSE'),
('TECH', 'Bio-Techne Corp.', 'NASDAQ'),
-- ヘルスケア - 製薬・流通追加
('HSIC', 'Henry Schein Inc.', 'NASDAQ'),
('VTRS', 'Viatris Inc.', 'NASDAQ'),
-- 金融 - 資産運用追加
('APO', 'Apollo Global Management Inc.', 'NYSE'),
('AMP', 'Ameriprise Financial Inc.', 'NYSE'),
('RJF', 'Raymond James Financial Inc.', 'NYSE'),
('SEIC', 'SEI Investments Co.', 'NASDAQ'),
('VOYA', 'Voya Financial Inc.', 'NYSE'),
('ACGL', 'Arch Capital Group Ltd.', 'NASDAQ'),
-- 金融 - 保険追加
('GL', 'Globe Life Inc.', 'NYSE'),
('LNC', 'Lincoln National Corp.', 'NYSE'),
('BRO', 'Brown & Brown Inc.', 'NYSE'),
-- 金融 - 銀行追加
('ALLY', 'Ally Financial Inc.', 'NYSE'),
('FHN', 'First Horizon Corp.', 'NYSE'),
('ZION', 'Zions Bancorporation N.A.', 'NASDAQ'),
-- 一般消費財 - 小売追加
('DG', 'Dollar General Corp.', 'NYSE'),
('DLTR', 'Dollar Tree Inc.', 'NASDAQ'),
('NCLH', 'Norwegian Cruise Line Holdings Ltd.', 'NYSE'),
('CPRI', 'Capri Holdings Ltd.', 'NYSE'),
('MHK', 'Mohawk Industries Inc.', 'NYSE'),
('DECK', 'Deckers Outdoor Corp.', 'NYSE'),
('HOG', 'Harley-Davidson Inc.', 'NYSE'),
('BC', 'Brunswick Corp.', 'NYSE'),
-- 一般消費財 - アパレル追加
('RL', 'Ralph Lauren Corp.', 'NYSE'),
('VFC', 'VF Corp.', 'NYSE'),
('TPR', 'Tapestry Inc.', 'NYSE'),
('PVH', 'PVH Corp.', 'NYSE'),
-- 一般消費財 - 玩具
('HAS', 'Hasbro Inc.', 'NASDAQ'),
('MAT', 'Mattel Inc.', 'NASDAQ'),
-- 一般消費財 - 家電
('WHR', 'Whirlpool Corp.', 'NYSE'),
-- 生活必需品追加
('CLX', 'Clorox Co.', 'NYSE'),
('KMB', 'Kimberly-Clark Corp.', 'NYSE'),
('REYN', 'Reynolds Consumer Products Inc.', 'NASDAQ'),
-- エネルギー - パイプライン追加
('OKE', 'ONEOK Inc.', 'NYSE'),
('KMI', 'Kinder Morgan Inc.', 'NYSE'),
('WMB', 'Williams Companies Inc.', 'NYSE'),
('LNG', 'Cheniere Energy Inc.', 'NYSE'),
('NOV', 'NOV Inc.', 'NYSE'),
-- 素材追加
('OLN', 'Olin Corp.', 'NYSE'),
('OC', 'Owens Corning', 'NYSE'),
('MAS', 'Masco Corp.', 'NYSE'),
('FBIN', 'Fortune Brands Innovations Inc.', 'NYSE'),
('TREX', 'Trex Co. Inc.', 'NYSE'),
('ATI', 'ATI Inc.', 'NYSE'),
('BLD', 'TopBuild Corp.', 'NYSE'),
-- 資本財 - 産業機械追加
('PNR', 'Pentair plc', 'NYSE'),
('ALLE', 'Allegion plc', 'NYSE'),
('NVT', 'nVent Electric plc', 'NYSE'),
('FLS', 'Flowserve Corp.', 'NYSE'),
('TRMB', 'Trimble Inc.', 'NASDAQ'),
('TKR', 'Timken Co.', 'NYSE'),
('ITT', 'ITT Inc.', 'NYSE'),
('MIDD', 'Middleby Corp.', 'NASDAQ'),
-- 資本財 - 人材・サービス追加
('RHI', 'Robert Half Inc.', 'NYSE'),
('MAN', 'ManpowerGroup Inc.', 'NYSE'),
('ACM', 'AECOM', 'NYSE'),
-- 資本財 - 輸送追加
('KNX', 'Knight-Swift Transportation Holdings Inc.', 'NYSE'),
('XPO', 'XPO Inc.', 'NYSE'),
('GXO', 'GXO Logistics Inc.', 'NYSE'),
('SAIA', 'Saia Inc.', 'NASDAQ'),
-- 公益事業追加
('ATO', 'Atmos Energy Corp.', 'NYSE'),
('OGE', 'OGE Energy Corp.', 'NYSE'),
('PNW', 'Pinnacle West Capital Corp.', 'NASDAQ'),
('NRG', 'NRG Energy Inc.', 'NYSE'),
('BKH', 'Black Hills Corp.', 'NYSE'),
('UGI', 'UGI Corp.', 'NYSE'),
-- 不動産 - 住宅追加
('UDR', 'UDR Inc.', 'NYSE'),
('CPT', 'Camden Property Trust', 'NYSE'),
('ESS', 'Essex Property Trust Inc.', 'NYSE'),
('ELS', 'Equity LifeStyle Properties Inc.', 'NYSE'),
('SUI', 'Sun Communities Inc.', 'NYSE'),
('AMH', 'American Homes 4 Rent', 'NYSE'),
-- 不動産 - ヘルスケア追加
('DOC', 'Healthpeak Properties Inc.', 'NYSE'),
-- 不動産 - 産業・物流追加
('COLD', 'Americold Realty Trust', 'NYSE'),
('FR', 'First Industrial Realty Trust Inc.', 'NYSE'),
('EGP', 'EastGroup Properties Inc.', 'NYSE'),
('REXR', 'Rexford Industrial Realty Inc.', 'NYSE'),
-- 不動産 - オフィス追加
('KRC', 'Kilroy Realty Corp.', 'NYSE'),
('DEI', 'Douglas Emmett Inc.', 'NYSE'),
-- 不動産 - サービス追加
('JLL', 'Jones Lang LaSalle Inc.', 'NYSE'),
-- 通信サービス追加
('SIRI', 'Sirius XM Holdings Inc.', 'NASDAQ'),
('Z', 'Zillow Group Inc.', 'NASDAQ'),
('IAC', 'IAC Inc.', 'NASDAQ'),
('WMG', 'Warner Music Group Corp.', 'NASDAQ'),
('NWSA', 'News Corp (Class A)', 'NASDAQ'),
('NWS', 'News Corp (Class B)', 'NASDAQ')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  market = EXCLUDED.market;
