// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// AddWatchlistRequest defines model for AddWatchlistRequest.
type AddWatchlistRequest struct {
	// SymbolCode 追加する銘柄コード（例: AAPL, 7203.T）
	SymbolCode string `binding:"required,min=1,max=20" json:"symbol_code"`
}

// CandleResponse defines model for CandleResponse.
type CandleResponse struct {
	// Close 終値
	Close float64 `json:"close"`

	// High 高値
	High float64 `json:"high"`

	// Low 安値
	Low float64 `json:"low"`

	// Open 始値
	Open float64 `json:"open"`

	// Time 日付（YYYY-MM-DD形式）
	Time string `json:"time"`

	// Volume 出来高
	Volume int64 `json:"volume"`
}

// CompanyAnalysisRequest defines model for CompanyAnalysisRequest.
type CompanyAnalysisRequest struct {
	// CompanyName 分析対象の企業名
	CompanyName string `binding:"required" json:"company_name"`
}

// CompanyAnalysisResponse defines model for CompanyAnalysisResponse.
type CompanyAnalysisResponse struct {
	// CompanyName 分析対象の企業名
	CompanyName string `json:"company_name"`

	// Summary AI生成の企業分析サマリー
	Summary string `json:"summary"`
}

// DetectedLogoResponse defines model for DetectedLogoResponse.
type DetectedLogoResponse struct {
	// Confidence 信頼度スコア（0.0 ~ 1.0）
	Confidence float32 `json:"confidence"`

	// Name 検出された企業名
	Name string `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error エラーメッセージ
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status サービスステータス
	Status string `json:"status"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email メールアドレス
	Email string `binding:"required,email" json:"email"`

	// Password パスワード
	Password string `binding:"required" json:"password"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// ReorderWatchlistRequest defines model for ReorderWatchlistRequest.
type ReorderWatchlistRequest struct {
	// Codes 新しい順序での銘柄コード一覧
	Codes []string `binding:"required,min=1" json:"codes"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	// Email メールアドレス
	Email string `binding:"required,email" json:"email"`

	// Password パスワード（8文字以上）
	Password string `binding:"required,min=8" json:"password"`
}

// SymbolItem defines model for SymbolItem.
type SymbolItem struct {
	// Code 銘柄コード（例: AAPL, 7203.T）
	Code string `json:"code"`

	// Name 企業名
	Name string `json:"name"`
}

// WatchlistItem defines model for WatchlistItem.
type WatchlistItem struct {
	// Id ウォッチリストエントリのID
	Id int `json:"id"`

	// SortKey 表示順序
	SortKey int `json:"sort_key"`

	// SymbolCode 銘柄コード（例: AAPL, 7203.T）
	SymbolCode string `json:"symbol_code"`
}

// GetCandlesParams defines parameters for GetCandles.
type GetCandlesParams struct {
	// Interval 時間間隔
	Interval *string `form:"interval,omitempty" json:"interval,omitempty"`

	// Outputsize 取得件数
	Outputsize *int `form:"outputsize,omitempty" json:"outputsize,omitempty"`
}

// DetectLogoMultipartBody defines parameters for DetectLogo.
type DetectLogoMultipartBody struct {
	// Image ロゴ検出対象の画像ファイル（最大10MB）
	Image openapi_types.File `json:"image"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// AnalyzeCompanyJSONRequestBody defines body for AnalyzeCompany for application/json ContentType.
type AnalyzeCompanyJSONRequestBody = CompanyAnalysisRequest

// DetectLogoMultipartRequestBody defines body for DetectLogo for multipart/form-data ContentType.
type DetectLogoMultipartRequestBody DetectLogoMultipartBody

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// AddToWatchlistJSONRequestBody defines body for AddToWatchlist for application/json ContentType.
type AddToWatchlistJSONRequestBody = AddWatchlistRequest

// ReorderWatchlistJSONRequestBody defines body for ReorderWatchlist for application/json ContentType.
type ReorderWatchlistJSONRequestBody = ReorderWatchlistRequest
