// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package symbollistsqlc

import (
	"context"
	"database/sql"
)

const listActiveSymbols = `-- name: ListActiveSymbols :many
SELECT id, code, name, market, timezone, logo_url, logo_updated_at, is_active, created_at, updated_at
FROM symbols
WHERE is_active = TRUE
ORDER BY code ASC
`

func (q *Queries) ListActiveSymbols(ctx context.Context) ([]Symbol, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Symbol{}
	for rows.Next() {
		var i Symbol
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Market,
			&i.Timezone,
			&i.LogoUrl,
			&i.LogoUpdatedAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const symbolExists = `-- name: SymbolExists :one
SELECT EXISTS (
  SELECT 1 FROM symbols WHERE code = $1
) AS exists
`

func (q *Queries) SymbolExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRowContext(ctx, symbolExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSymbolLogoURL = `-- name: UpdateSymbolLogoURL :execrows
UPDATE symbols
SET logo_url = $2,
    logo_updated_at = $3,
    updated_at = now()
WHERE code = $1
`

type UpdateSymbolLogoURLParams struct {
	Code          string
	LogoUrl       sql.NullString
	LogoUpdatedAt sql.NullTime
}

func (q *Queries) UpdateSymbolLogoURL(ctx context.Context, arg UpdateSymbolLogoURLParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSymbolLogoURL, arg.Code, arg.LogoUrl, arg.LogoUpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
