// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package symbollistsqlc

import (
	"context"
)

type Querier interface {
	ListActiveSymbols(ctx context.Context) ([]Symbol, error)
	SymbolExists(ctx context.Context, code string) (bool, error)
	UpdateSymbolLogoURL(ctx context.Context, arg UpdateSymbolLogoURLParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
