FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache git build-base tzdata
ENV TZ=Asia/Tokyo

RUN go install github.com/air-verse/air@v1.62.0

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
