FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# APIサーバ
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server

FROM alpine:3.21
WORKDIR /app

RUN apk add --no-cache tzdata
ENV TZ=Asia/Tokyo

COPY --from=builder /app/server .

EXPOSE 8080
CMD ["./server"]