// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package watchlistsqlc

import (
	"context"
)

type Querier interface {
	DeleteWatchlist(ctx context.Context, arg DeleteWatchlistParams) (int64, error)
	InsertWatchlist(ctx context.Context, arg InsertWatchlistParams) error
	ListWatchlistByUser(ctx context.Context, userID int64) ([]Watchlist, error)
	MaxWatchlistSortKey(ctx context.Context, userID int64) (int64, error)
	UpdateWatchlistSortKey(ctx context.Context, arg UpdateWatchlistSortKeyParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
