// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package watchlistsqlc

import (
	"context"
)

const deleteWatchlist = `-- name: DeleteWatchlist :execrows
DELETE FROM watchlists
WHERE user_id = $1 AND symbol_code = $2
`

type DeleteWatchlistParams struct {
	UserID     int64
	SymbolCode string
}

func (q *Queries) DeleteWatchlist(ctx context.Context, arg DeleteWatchlistParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWatchlist, arg.UserID, arg.SymbolCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertWatchlist = `-- name: InsertWatchlist :exec
INSERT INTO watchlists (user_id, symbol_code, sort_key)
VALUES ($1, $2, $3)
`

type InsertWatchlistParams struct {
	UserID     int64
	SymbolCode string
	SortKey    int64
}

func (q *Queries) InsertWatchlist(ctx context.Context, arg InsertWatchlistParams) error {
	_, err := q.db.ExecContext(ctx, insertWatchlist, arg.UserID, arg.SymbolCode, arg.SortKey)
	return err
}

const listWatchlistByUser = `-- name: ListWatchlistByUser :many
SELECT id, user_id, symbol_code, sort_key, created_at, updated_at
FROM watchlists
WHERE user_id = $1
ORDER BY sort_key ASC
`

func (q *Queries) ListWatchlistByUser(ctx context.Context, userID int64) ([]Watchlist, error) {
	rows, err := q.db.QueryContext(ctx, listWatchlistByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Watchlist{}
	for rows.Next() {
		var i Watchlist
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SymbolCode,
			&i.SortKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxWatchlistSortKey = `-- name: MaxWatchlistSortKey :one
SELECT COALESCE(MAX(sort_key), -1)::bigint AS max_key
FROM watchlists
WHERE user_id = $1
`

func (q *Queries) MaxWatchlistSortKey(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxWatchlistSortKey, userID)
	var max_key int64
	err := row.Scan(&max_key)
	return max_key, err
}

const updateWatchlistSortKey = `-- name: UpdateWatchlistSortKey :execrows
UPDATE watchlists
SET sort_key = $3,
    updated_at = now()
WHERE user_id = $1 AND symbol_code = $2
`

type UpdateWatchlistSortKeyParams struct {
	UserID     int64
	SymbolCode string
	SortKey    int64
}

func (q *Queries) UpdateWatchlistSortKey(ctx context.Context, arg UpdateWatchlistSortKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWatchlistSortKey, arg.UserID, arg.SymbolCode, arg.SortKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
