// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package candlessqlc

import (
	"context"
)

type Querier interface {
	FindCandlesAll(ctx context.Context, arg FindCandlesAllParams) ([]FindCandlesAllRow, error)
	FindCandlesLimit(ctx context.Context, arg FindCandlesLimitParams) ([]FindCandlesLimitRow, error)
}

var _ Querier = (*Queries)(nil)
