// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authsqlc

import (
	"context"
)

type Querier interface {
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindOAuthAccountByProvider(ctx context.Context, arg FindOAuthAccountByProviderParams) (OauthAccount, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id int64) (User, error)
}

var _ Querier = (*Queries)(nil)
