CREATE TABLE IF NOT EXISTS symbols (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    market VARCHAR(100) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_key BIGINT NOT NULL DEFAULT 0,
    updated_at DATETIME(3),
    UNIQUE INDEX idx_symbols_code (code)
);
