// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authsqlc

import (
	"database/sql"
	"time"
)

type Candle struct {
	ID         int64
	SymbolCode string
	Interval   string
	Time       time.Time
	Open       string
	High       string
	Low        string
	Close      string
	Volume     int64
}

type OauthAccount struct {
	ID          int64
	UserID      int64
	Provider    string
	ProviderUid string
	CreatedAt   time.Time
}

type Symbol struct {
	ID            int64
	Code          string
	Name          string
	Market        string
	Timezone      string
	LogoUrl       sql.NullString
	LogoUpdatedAt sql.NullTime
	IsActive      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID        int64
	Email     string
	Password  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Watchlist struct {
	ID         int64
	UserID     int64
	SymbolCode string
	SortKey    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
